name: Daily Scraper and Render Deploy

on:
  schedule:
    - cron: "0 0 * * *"  # Runs at midnight UTC every day
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          pip install -r webScrapper/requirements.txt

      - name: Run Scraper
        run: python webScrapper/scraper.py
      
      - name: Run Cleaner
        run: python webScrapper/cleaner.py

      - name: Commit and Push Data
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add webScrapper/historical_food_products.csv
          git commit -m "Update CSV with new data" || echo "No changes to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/SeijiUeno/Food_Prices_WebScrapper.git HEAD:main

      - name: Trigger Render Deploy
        env:
          RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl -X POST "$RENDER_DEPLOY_HOOK_URL"


